version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      - IS_PERSISTENT=TRUE      

  fastapi-app:
    build: .
    container_name: fastapi-app
    restart: always
    depends_on:
      - postgres
      - chromadb
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/mydatabase"
      CHROMADB_URL: "http://locahhost:8001"
    volumes:
      - .:/app

volumes:
  postgres_data:
  chroma_data:
